  main = ".open-next/worker.js"
  name = "rawuh-dashboard"
  compatibility_date = "2026-01-06"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"